apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-dom
  namespace: pos-sale-dom
  labels:
    app: pos-dom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pos-dom
  template:
    metadata:
      labels:
        app: pos-dom
    spec:
      containers:
        - name: pos-dom
          image: kmontes2020/erp-kynsoft-odoo-v18:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8069
          volumeMounts:
            - name: filestore
              mountPath: /var/lib/odoo
            - name: odoo-conf-v
              mountPath: /etc/odoo
              readOnly: true
      volumes:
        - name: filestore
          persistentVolumeClaim:
            claimName: pos-dom-data-pvc
        - name: odoo-conf-v
          configMap:
            name: pos-dom
