apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-prod-data-pvc
  namespace: erp-kynsoft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # No storageClassName = uses default (local-path)
