apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odata-v17-pvc
  namespace: medinec-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # No storageClassName = uses default (local-path)
