apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pos-dom-pvc
  namespace: pos-sale-dom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  # No storageClassName = uses default (local-path)
