apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pos-dom-data-pvc
  namespace: pos-sale-dom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # No storageClassName = uses default (local-path)
